### ISSUE TITLE
Does OpenSearch have any blocking issue with the NFS storage class?

### ISSUE THREAD

**Issue by balar06** [opensearch-project/documentation-website#566] opened 2022-05-11 13:24 UTC
since Elasticsearch did not recommend the NFS storage class due to latency issues and other factors, seems the same applies to OpenSearch.

Does OpenSearch have any blocking issue with the NFS storage class?

**Comment by balar06** [comment] 2022-05-12 12:32
Performed some test cases in k8 cluster with NFS storage class, but couldn't find any blocking issue with NFS storage.

**Comment by nateynateynate** [comment] 2022-05-13 20:34
@balar06 - I've taken the liberty of filing https://github.com/opensearch-project/documentation-website/issues/569 on your behalf to see if anyone wants to take a crack at it.

**Comment by JeffH-AWS** [comment] 2022-08-16 20:01
Should we close out this issue since https://github.com/opensearch-project/documentation-website/issues/569 was raised?  There doesn't seem to be anything actionable here that isn't covered by the broader FR in 569.

**Comment by JeffH-AWS** [comment] 2022-08-17 20:36
I'm going to close this out for now since it's a dupe of the issue Nate opened.

**Closed by JeffH-AWS** 2022-08-17 20:36 UTC
Labels: feedback needed
