### ISSUE TITLE
[DOC] Update documentation to reflect PPL support for cross cluster queries

### ISSUE THREAD

**Issue by nitincd** [opensearch-project/documentation-website#3512] opened 2023-03-16 21:15 UTC
**What do you want to do?**
 
- [] Request a change to existing documentation
- [X] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 We need to add information about the newly added ability for PPL to do cross cluster queries

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

**Comment by Naarcha-AWS** [comment] 2023-03-17 20:21
@nitincd: Is this related to a specific version of OpenSearch?

**Comment by hdhalter** [comment] 2023-03-17 22:14
Looks like this is a 2.7 feature: 

Description of Feature: We are planning to add Cross Cluster support for PPL/SQL queries. Today, customers are able to use PPL/SQL to query and visualize the data stored in an index in an OpenSearch cluster. However, this is limited to indexes on one cluster. We seek to enhance this capability so that the customers can fetch data from multiple OpenSearch clusters across domain boundaries. We are only looking to extend this capability for OpenSearch indexes and not looking to fetch data from other kinds of databases (waiting on Neo for that).

**Comment by hdhalter** [comment] 2023-03-17 22:15
Dev issue: https://github.com/opensearch-project/sql/issues/789

**Comment by hdhalter** [comment] 2023-05-04 19:24
Here's some initial documentation on the feature: https://github.com/opensearch-project/sql/blob/main/docs/user/ppl/admin/cross_cluster_search.rst

The issue is related to this: https://opensearch.org/docs/latest/security/access-control/cross-cluster-search/

**Comment by hdhalter** [comment] 2023-06-01 20:10
Reassigning to Fanit. We will add this section under PPL, and move PPL topics under Observability.

**Closed** 2023-06-06 16:23 UTC
Labels: 1 - Backlog, v2.8.0
