### ISSUE TITLE
[DOC] Create documentation for ML Model Health Dashboard

### ISSUE THREAD

**Issue by wanglam** [opensearch-project/documentation-website#2963] opened 2023-02-20 06:38 UTC
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [X] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 We plan to experiment with the OpenSearch Dashboard plugin of ml-commons-dashboard in version 2.6. This plugin is mainly used to view the responding status of machine learning models at different machine learning nodes. We need more detailed documents to explain the relevant functions of this plugin.

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.
N/A

**Comment by Naarcha-AWS** [comment] 2023-02-20 16:52
This is a duplicate of #2240. Closing for now.

**Closed by Naarcha-AWS** 2023-02-20 16:52 UTC
Labels: untriaged
