### ISSUE TITLE
[DOC] `Dead Letter Queues` link in OpenSearch Sink points to invalid link

### ISSUE THREAD

**Issue by kkondaka** [opensearch-project/documentation-website#5201] opened 2023-10-13 23:32 UTC
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [ ] Add new documentation
- [X ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.

Clicking on `Dead Letter Queues` link in https://github.com/opensearch-project/documentation-website/blob/main/_data-prepper/pipelines/configuration/sinks/opensearch.md reports page not found.
 

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

**Comment by BigSamu** [comment] 2023-10-16 08:45
@Naarcha-AWS I would like to work on this issue

**Comment by BigSamu** [comment] 2023-10-20 15:15
@Naarcha-AWS,

Upon investigation of this issue, the problems appears to be bigger. There are many dead links, mainly because the change of name in the folder preappending a "_" before them. Below I attach you more examples of dead links under the section `_data_prepper`:

- [Link 1](https://github.com/opensearch-project/documentation-website/blob/main/_data-prepper/%7B%7Bsite.url%7D%7D%7B%7Bsite.baseurl%7D%7D/clients/data-prepper/get-started)
- [Link 2](https://github.com/opensearch-project/documentation-website/blob/main/_data-prepper/pipelines/%7B%7Bsite.url%7D%7D%7B%7Bsite.baseurl%7D%7D/data-prepper/pipelines/configuration/sinks/sinks)
- [Link 3] (https://github.com/opensearch-project/documentation-website/blob/main/_data-prepper/pipelines/configuration/sinks/%7B%7Bsite.url%7D%7D%7B%7Bsite.baseurl%7D%7D/security/access-control/users-roles/#map-users-to-roles)

There are several more examples with dead links. Any suggestion of how to proceed? Do you have any script that can detect dead links given a pattern?

Regards,

Samuel

**Comment by BigSamu** [comment] 2023-10-20 15:51
@kkonda,

Could you give more details about the dead link you refer to? I am navigating through the [Documentation Website](https://opensearch.org/docs/latest/data-prepper/pipelines/configuration/sinks/opensearch/), in the section you refer (`data-prepper/pipelines/configuration/sinks/opensearch/`) and I don't see any error as you mentioned.
 
Check here the [link](https://opensearch.org/docs/latest/data-prepper/pipelines/dlq/) for Dead-letter queues. It is working correctly. 

**Remember that you need to check the documentation website, not the links created in the Github repo.**

Regards,

Samuel

**Comment by BigSamu** [comment] 2023-10-24 15:30
Hi @kkondaka,

Any chance of reviewing my previous response? Want to check if we close this issue or not.

Regards,

Samuel

**Comment by kkonda** [comment] 2023-10-24 15:31
Not a chance from me

**Comment by BigSamu** [comment] 2023-10-27 10:01
@Naarcha-AWS, I think this issue does not have any problem at all. We should close it. Documentation is working correctly in this case.

Regards,

Samuel

**Comment by Naarcha-AWS** [comment] 2023-10-31 15:30
I also validated the issue is solved. Closing now.

**Closed by Naarcha-AWS** 2023-10-31 15:30 UTC
Labels: 1 - Backlog, OSCI
