### ISSUE TITLE
[DOC] Enumerate Filters and Tokenizers AVailable

### ISSUE THREAD

**Issue by nateynateynate** [opensearch-project/documentation-website#790] opened 2022-07-11 21:02 UTC
### Is your feature request related to a problem?
We're missing a piece of documentation regarding what filters and tokenizers are available on OpenSearch.

### What solution would you like?
_A new documentation page with a table that enumerates the available tokenizers and filters are available_

### Do you have any additional context?
https://forum.opensearch.org/t/built-in-filters-and-tokenizers-available-in-opensearch-from-elasticsearch/10229

**Comment by macohen** [comment] 2023-09-14 16:13
Does this list of, hopefully all, token filters help? https://gist.github.com/macohen/9f335a741677fac2e916cf980f8019fe

**Comment by hdhalter** [comment] 2023-11-10 01:53
@kolchfa-aws  - is this a duplicate of https://github.com/opensearch-project/documentation-website/issues/1483?

**Comment by kolchfa-aws** [comment] 2023-11-10 15:13
@hdhalter  #1483 only mentions analyzers. This one mentions tokenizers and token filters. So they are different. That said, I already added a [page listing all token filters](https://opensearch.org/docs/latest/analyzers/token-filters/index/)

**Comment by rursprung** [comment] 2024-01-05 08:02
i think it's important that this gets documented (though for now one can still look at the ES documentation as they're largely the same). i was just searching for some specific documentation for a tokenizer only to find that none of them are currently documented.

**Closed** 2024-01-18 20:05 UTC
Labels: 1 - Backlog, v-All, Content gap
