### ISSUE TITLE
[Improvement] Docs for Saved Object & other elements of Dashboards architecture 

### ISSUE THREAD

**Issue by ashwin-pc** [opensearch-project/documentation-website#173] opened 2021-09-14 01:24 UTC
I know we have plans to improve documentation as a whole, but in the interim, do we have any plans on matching the documentation elastic already has?

For example, while building my plugin, I needed to understand what saved objects in Dashboards are, and the only [doc](https://www.elastic.co/guide/en/kibana/7.x/saved-objects-service.html) i can find that explains this is from elastic. 

This is similar to #171. Feel free to close this and combine it with that if they are the same

**Comment by aetter** [comment] 2021-09-14 22:34
Hey @ashwin-pc, yep, I'd call this a duplicate of #171. It's a known issue that we're unlikely to tackle this year.

**Closed by aetter** 2021-09-14 22:34 UTC
