### ISSUE TITLE
[DOC] Add documentation for date-math

### ISSUE THREAD

**Issue by zhongnansu** [opensearch-project/documentation-website#1867] opened 2022-11-14 20:08 UTC
**What do you want to do?**
 "Acceptable date format" helper link in OpenSearch Dashboards  is pointing to documentation home page.

<img width="424" alt="screen_shot_2022-11-09_at_12 14 59_pm" src="https://user-images.githubusercontent.com/28733332/200968655-fb604089-9308-475c-b398-aa93c4cc9279.png">

- [ ] Request a change to existing documentation
- [x] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
- Issue submitted from community(OpenSearch Dashboards repo). https://github.com/opensearch-project/OpenSearch-Dashboards/issues/2849
- part of https://github.com/opensearch-project/documentation-website/issues/1853

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

**Comment by JeffH-AWS** [comment] 2022-11-30 18:18
@zhongnansu can you please explain what the issue is? I'm not sure what you mean by:
```
"Acceptable date format" helper link in OpenSearch Dashboards is pointing to documentation home page.
```

Please provide a summary of the current state, what exactly is wrong, and what it should look like when it's fixed.

**Comment by hdhalter** [comment] 2022-11-30 20:52
Hi Jeff, I believe they are asking for documentation to be created for this feature. Currently, the link from dashboards is going to our home page. As soon as we create documentation and provide a link, they'll update the link in the UI.

**Comment by hdhalter** [comment] 2022-11-30 20:53
@kolchfa-aws - do you know if we have documentation on this?

**Comment by kolchfa-aws** [comment] 2022-11-30 21:41
We do have documentation on acceptable date formats (https://opensearch.org/docs/latest/opensearch/supported-field-types/date/#formats), but I don't think the intent is to link to date formats. What Dashboards page is this from? Does it need to link to date formats or date math? If it needs to link to date math, the only mention of it that we have is in the [term queries](https://opensearch.org/docs/latest/opensearch/query-dsl/term/) and [bucket aggregations](https://opensearch.org/docs/latest/opensearch/bucket-agg/) pages, where it's used. But we don't have a dedicated page for date math.

**Comment by kolchfa-aws** [comment] 2022-11-30 21:47
@JeffH-AWS @hdhalter You can assign this one to me if you want.

**Comment by hdhalter** [comment] 2022-12-01 23:49
Thanks for taking care of this, Fanit! When you are done, please let joshuarrrr know so he can fix the link.

**Closed** 2023-01-06 16:00 UTC
Labels: dashboards
