### ISSUE TITLE
[DOC] Alerting - Destination migration to notification

### ISSUE THREAD

**Issue by kamingleung** [opensearch-project/documentation-website#1994] opened 2022-11-21 20:07 UTC
**What do you want to do?**
 
- [x] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
Since 2.0, a centralized notification plugin was introduced to replace the destinations within alerting. 
In alerting documentation, the Destinations section should be updated:
- It should inform users that Destinations has been replaced with the Notifications plugin
- It should be clear that the destinations are automatically migrated into channels in Notifications plugin
- There may be cases some destinations are unable to auto-migrate (e.g.: due to cluster write block), the documentation can guide users on what to do in those situations.
- Users won't be able to create or configure destinations, they will need to go to the Notifications plugin to create or configure channels.

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.
https://opensearch.org/docs/2.4/monitoring-plugins/alerting/monitors/#create-destinations

@qreshi Can you provide more context for the documentation?

**Comment by qreshi** [comment] 2022-11-22 19:19
For reference, here was the original PR that added the Notifications contents to the documentation: https://github.com/opensearch-project/documentation-website/pull/586. We can use this as a base for improvements.

I noticed that there was a regression in the documentation website as well. You'll notice [things that we removed for Destinations in that original PR](https://github.com/opensearch-project/documentation-website/pull/586/files#diff-84890c1e896f001520a4397fcf87cf33ae70edd6bd059ec94f0d85cef5abc654L50) has since been [added back in somehow](https://github.com/opensearch-project/documentation-website/blob/main/_monitoring-plugins/alerting/monitors.md#create-destinations). This may have been because of an incorrect merge. Let's also amend that as part of this issue.

In the meantime, I'll think through what additional context we can provide based on what @kamingleung has mentioned above.

**Comment by Naarcha-AWS** [comment] 2022-11-22 19:50
@kamingleung and @qreshi: To clarify the ask here, whoever is assigned to this issue should do the following:

1. Remove the destinations section text for OpenSeach 2.0 and greater.
2. Add a note on the monitors page that monitors are now created in the notifications plugin.
3. Guidance on how to migrate destinations that are not automatically migrated to notifications. 

Do you have any notes on what the guidance for item #3 should be? Any resources besides that original PR?

**Comment by qreshi** [comment] 2022-11-22 20:02
@Naarcha-AWS Personally, for #3, I believe we had already answered that [here](https://github.com/opensearch-project/documentation-website/pull/586/files#diff-84890c1e896f001520a4397fcf87cf33ae70edd6bd059ec94f0d85cef5abc654R364-R365). Alerting continues to attempt migration until all Destinations have migrated. If migration fails, it uses the Destination as a fallback seamlessly, there should be no user intervention needed here (fixing the underlying cluster issue is a separate matter though).

Now if we don't think the current location for that information is the best place for it, that's valid and I'm open to suggestions there.

**Comment by qreshi** [comment] 2022-11-22 20:04
Some more technical details on this migration were mentioned in the [PR that added it to Alerting](https://github.com/opensearch-project/alerting/pull/379) if we want to include any of that in the documentation.

**Comment by kamingleung** [comment] 2022-11-22 20:31
Sorry, I didn't realize there is already a section on "Questions about Destinations". I believe items 2 & 3 are covered in that section. 

For item 3: For failed migrations, would it make sense to also recommend users to recreate the destination as channel and update the monitor to use the new channel?

**Comment by qreshi** [comment] 2022-11-22 21:03
> For item 3: For failed migrations, would it make sense to also recommend users to recreate the destination as channel and update the monitor to use the new channel?

@kamingleung If the migration is failing it is presumably because the indexing of the config has failed somehow (if it's transient it'll work the next time the job runs). In cases like this, they have bigger problems with the cluster as all writes would be failing. We want to avoid manual intervention here and should not recommend it. Let's keep it hands off for now. If we start seeing customer issues though of persistent errors that are because of the migration itself and not underlying cluster problems, then I think we should invest in manual alternatives.

**Closed** 2024-04-16 21:22 UTC
Labels: 2 - In progress, alerting
