### ISSUE TITLE
Upgrade documentation between versions of OpenSearch

### ISSUE THREAD

**Issue by SomanathThilak** [opensearch-project/documentation-website#2497] opened 2023-01-19 13:37 UTC
I am doing a upgrade to opensearch version 2.4 . Can someone point me to the documentation for opensearch upgrade/rollback procedure.

I could find document procedure only for upgrade(migration) from elasticsearch to opensearch.

**Comment by dblock** [comment] 2023-01-25 23:56
The URL https://opensearch.org/docs/latest/upgrade-to/upgrade-to/ has a double upgrade-to, which is weird.

We need a section under install and configure on upgrading between versions.

Generally the process is the same as from ES to OpenSearch, you'd want to check breaking changes (https://opensearch.org/docs/2.0/breaking-changes/) and do either a rolling or a restart upgrade.

**Comment by hdhalter** [comment] 2023-01-26 00:43
The upgrade documentation is in progress: https://github.com/opensearch-project/documentation-website/pull/2117

**Comment by hdhalter** [comment] 2023-01-30 23:55
Assigning to @JeffH-AWS , as he is working on the upgrade instructions.

**Comment by SomanathThilak** [comment] 2023-01-31 02:47
@dblock  Thanks for the update. 

@hdhalter  The pull request you have mentioned seems to be related to upgrades in docker environment.

We are using a RPM based deployment. Is that documentation common for both docker and RPM based deployments.

**Comment by JeffH-AWS** [comment] 2023-01-31 19:01
This is a duplicate of https://github.com/opensearch-project/documentation-website/issues/745

Please feel free to add comments on the meta issue! I'm closing this one as a duplicate.

**Closed by JeffH-AWS** 2023-01-31 19:01 UTC
Labels: Closed - Duplicate or Cancelled
